# Generated by Django 3.2.5 on 2022-08-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='img/default.jpeg', upload_to='img/')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('about', models.TextField(default='About Me')),
                ('git_link', models.URLField(default='https://github.com/Gaurav065')),
                ('link_link', models.URLField(default='https://www.linkedin.com/in/gaurav-patel-a822931bb/')),
                ('phone_number', models.CharField(default='+91-9721645391', max_length=15)),
                ('email', models.EmailField(default='gaurav.patel.gpp@gmail.com', max_length=254)),
            ],
        ),
    ]
