# Generated by Django 3.2.5 on 2022-08-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/default.jpeg', upload_to='img/'),
        ),
    ]
