# Generated by Django 3.2.5 on 2022-08-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default='About Me'),
        ),
        migrations.AddField(
            model_name='profile',
            name='git_link',
            field=models.URLField(default='https://github.com/Gaurav065'),
        ),
        migrations.AddField(
            model_name='profile',
            name='link_link',
            field=models.URLField(default='https://www.linkedin.com/in/gaurav-patel-a822931bb/'),
        ),
    ]
