# Generated by Django 3.2.5 on 2022-08-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20220821_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='gaurav.patel.gpp@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='+91-9721645391', max_length=15),
        ),
    ]
