# Generated by Django 3.2.5 on 2022-08-16 04:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Soul_Shift_HoriZon', '0002_auto_20220814_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='Info',
        ),
    ]
