# Generated by Django 3.2.5 on 2022-08-16 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Soul_Shift_HoriZon', '0003_rename_message_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skil',
            new_name='skill',
        ),
    ]
