# Generated by Django 3.2.5 on 2022-08-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Soul_Shift_HoriZon', '0004_rename_skil_skill_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='skil',
        ),
    ]
