# Generated by Django 4.1.1 on 2022-09-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitter',
            name='hit_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hitter',
            name='hit_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
