# Generated by Django 3.2.5 on 2022-08-21 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0002_auto_20220821_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements', models.CharField(default='Current work', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('link', models.URLField(default='https://github.com/Gaurav065')),
                ('description', models.TextField(default=models.CharField(max_length=100), max_length=300)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.experiance')),
                ('sk', models.ManyToManyField(related_name='sk', to='resume.skill')),
            ],
        ),
    ]
