# Generated by Django 3.2.5 on 2022-08-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_member', models.CharField(max_length=100)),
                ('member_level', models.IntegerField(default=0)),
                ('member_role', models.CharField(max_length=75)),
            ],
        ),
    ]
