# Generated by Django 3.2.5 on 2022-08-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='notes',
            field=models.TextField(default='No notes', max_length=300),
        ),
    ]
