# Generated by Django 3.2.5 on 2022-08-17 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0002_party_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='party_member_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('skills', models.CharField(default='basic survival', max_length=500)),
                ('skill_level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20)])),
                ('blessings', models.TextField(default='natural Hp and Mana regin')),
                ('rank', models.CharField(default='G', max_length=1)),
            ],
        ),
    ]
