# Generated by Django 3.2.5 on 2022-08-18 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0004_party_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='quests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_party', models.CharField(default='Herb collection', max_length=300)),
                ('quest_rank', models.CharField(default='F', max_length=1)),
                ('quest_time', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
