# Generated by Django 3.2.5 on 2022-08-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0005_quests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quests',
            new_name='quest',
        ),
    ]
