# Generated by Django 3.2.5 on 2022-08-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0007_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party_info',
            name='party_name',
        ),
        migrations.AddField(
            model_name='party',
            name='party_id',
            field=models.CharField(default='Duo Party', max_length=100),
        ),
    ]
