# Generated by Django 3.2.5 on 2022-08-21 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='best programmer', max_length=100)),
                ('url', models.URLField()),
                ('certi', models.ImageField(default='img/Screenshot 2022-08-21 054646.png', upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(default='Lovely Professional University', max_length=100)),
                ('course', models.CharField(default='B.Tech CSE with specialization In ML and AI', max_length=100)),
                ('gpa', models.FloatField(default=7.54, max_length=10.0)),
                ('date_start', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('date_end', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('location', models.CharField(default='Phagwara, Punjab, India, 144411', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='experiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('1', 'Frontend dev'), ('2', 'Backend dev'), ('3', 'Full Stack'), ('4', 'Software developer'), ('5', 'Data Scientist'), ('6', 'Data Engineer'), ('7', 'Database Administrator'), ('8', 'Machine Learning Engineer'), ('9', 'Software Architect'), ('10', 'Dev Ops Engineer'), ('11', 'Cloud Engineer'), ('12', 'IT project Manager'), ('13', 'Enterprise Architect')], default='None', max_length=200)),
                ('company_name', models.CharField(default='Client_Based', max_length=100)),
                ('job_type', models.CharField(choices=[('1', 'Internship'), ('2', 'Full time'), ('3', 'Part Time'), ('4', 'Freelancing')], default='None', max_length=200)),
                ('description', models.TextField(default=models.CharField(choices=[('1', 'Frontend dev'), ('2', 'Backend dev'), ('3', 'Full Stack'), ('4', 'Software developer'), ('5', 'Data Scientist'), ('6', 'Data Engineer'), ('7', 'Database Administrator'), ('8', 'Machine Learning Engineer'), ('9', 'Software Architect'), ('10', 'Dev Ops Engineer'), ('11', 'Cloud Engineer'), ('12', 'IT project Manager'), ('13', 'Enterprise Architect')], default='None', max_length=200), max_length=300)),
                ('location', models.CharField(default='India', max_length=50)),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Python', max_length=25)),
                ('typeof', models.CharField(choices=[('P', 'Programming Language'), ('M', 'Modules/Libraries'), ('T', 'Tools'), ('D', 'Databases')], default='Programminng', max_length=20)),
            ],
        ),
    ]
