# Generated by Django 3.2.5 on 2022-08-20 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(default='Lovely Professional University', max_length=100)),
                ('course', models.CharField(default='B.Tech CSE with specialization In ML and AI', max_length=100)),
                ('gpa', models.FloatField(default=7.54, max_length=10.0)),
                ('date_start', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('date_end', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
