# Generated by Django 3.2.5 on 2022-08-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='typeof',
            field=models.CharField(choices=[('P', 'Programming Language'), ('M', 'Modules/Libraries'), ('T', 'Tools'), ('D', 'Databases')], default='P', max_length=20),
        ),
    ]
