# Generated by Django 3.2.5 on 2022-08-21 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certi', models.ImageField(default='img/Screenshot 2022-08-21 054646.png', upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='experiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('1', 'Frontend dev'), ('2', 'Backend dev'), ('3', 'Full Stack'), ('4', 'Software developer'), ('5', 'Data Scientist'), ('6', 'Data Engineer'), ('7', 'Database Administrator'), ('8', 'Machine Learning Engineer'), ('9', 'Software Architect'), ('10', 'Dev Ops Engineer'), ('11', 'Cloud Engineer'), ('12', 'IT project Manager'), ('13', 'Enterprise Architect')], default='None', max_length=200)),
                ('company_name', models.CharField(default='Client_Based', max_length=100)),
                ('job_type', models.CharField(choices=[('1', 'Internship'), ('2', 'Full time'), ('3', 'Part Time'), ('4', 'Freelancing')], default='None', max_length=200)),
                ('description', models.TextField(default=models.CharField(choices=[('1', 'Frontend dev'), ('2', 'Backend dev'), ('3', 'Full Stack'), ('4', 'Software developer'), ('5', 'Data Scientist'), ('6', 'Data Engineer'), ('7', 'Database Administrator'), ('8', 'Machine Learning Engineer'), ('9', 'Software Architect'), ('10', 'Dev Ops Engineer'), ('11', 'Cloud Engineer'), ('12', 'IT project Manager'), ('13', 'Enterprise Architect')], default='None', max_length=200), max_length=300)),
                ('location', models.CharField(default='India', max_length=50)),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_languages', models.CharField(choices=[('1', 'Python'), ('2', 'Java'), ('3', 'C'), ('4', 'C++'), ('5', 'C#'), ('6', 'Rust'), ('7', 'GoLang'), ('8', 'SQL'), ('9', 'PHP'), ('10', 'Scala'), ('11', 'Swift'), ('12', 'Matlab'), ('13', 'Kotlin'), ('14', 'Node.js'), ('15', 'React.js'), ('16', 'CSS'), ('17', 'HTML'), ('18', 'TypeScript'), ('19', 'Ruby')], default='Python', max_length=100)),
                ('modules_libraries', models.CharField(default='python libraries', max_length=400)),
                ('tools', models.CharField(default='VS code, Github, pyqt designer, unreal engine, adobe, etc', max_length=200)),
                ('databases', models.CharField(choices=[('1', 'MongoDB'), ('2', 'Postgres'), ('3', 'MySQL')], default='SQL', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(default='Phagwara, Punjab, India, 144411', max_length=150),
        ),
    ]
